batch_size: 24
learning_rate: 0.00002
epochs: 3
weight_decay: 0.01
model_name: "distilbert-base-cased"
train_file: "data/POS/fake_translate_train.tagged"
val_file: "data/POS/fake_translate_val.tagged"
test_file: "data/POS/fake_translate_test.tagged"
